### PR TITLE
Crypto Stats: React capstone project

### PR DESCRIPTION
**Pull request by gitbygaurav**
### Hey CR 👋,

0001GIF

Crypto stats is a web app that shows the data of cryptocurrencies, It is a single-page application which has 2 routes one for home and another for details of selected coin.

It is built with:-

- React and redux
- Redux toolkit
- Coinstats Api
- React router

Thanks 🍻

### CODE REVIEW

**Review by Abenezer-Tilahun — CHANGES_REQUESTED** [review]
Hi @gauravgangwarweb     , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git-Flow.
✔️ Good commit messages
✔️ Professional README file.

almost

## Required Changes ♻️

- [ ] Good Job for Implementing  test requirement but When I run test cases one of the test case(details.test.js) is failed as shown below, Kindly Fix it.

Capture


_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gitbygaurav** [comment]
Hii @Abenezer-Tilahun 

Thanks for reviewing my PR and suggesting me the changes I will fix those issues.

Happy coding😊

**Review by DammyShittu — APPROVED** [review]
Hi @gauravgangwarweb,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gitbygaurav** [comment]
Hii @DammyShittu 👋
Thanks for reviewing and approving my PR.
ThankYouStickerThanksStickerGIF

**Pull request merged**
